/**
 * CON-01 JSON-Schema-compatible closed descriptors (no runtime schema package).
 */

export const CONTRACT_DESCRIPTORS_V1: Record<string, unknown> = {
	"role-request": {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		type: "object",
		additionalProperties: false,
		required: [
			"schemaVersion",
			"kind",
			"taskId",
			"role",
			"phase",
			"goal",
			"writeScope",
			"ownedPaths",
			"forbiddenPaths",
			"tools",
			"model",
			"thinking",
			"budget",
			"artifacts",
		],
		properties: {
			schemaVersion: { const: 1 },
			kind: { const: "role-request" },
			taskId: { type: "string", minLength: 1 },
			role: {
				type: "string",
				enum: [
					"specifier",
					"test-designer",
					"implementer",
					"breaker",
					"fitness-guardian",
					"refactorer",
					"qa",
				],
			},
			phase: { type: "string", minLength: 1 },
			goal: { type: "string", minLength: 1 },
			writeScope: { type: "string", enum: ["none", "tests", "production"] },
			ownedPaths: { type: "array", items: { type: "string" } },
			forbiddenPaths: { type: "array", items: { type: "string" } },
			tools: { type: "array", items: { type: "string" } },
			model: { type: "string" },
			thinking: { type: "string" },
			budget: {
				type: "object",
				additionalProperties: false,
				required: ["maxTokens", "maxCostUsd", "maxDurationMs"],
				properties: {
					maxTokens: { type: "number" },
					maxCostUsd: { type: "number" },
					maxDurationMs: { type: "number" },
				},
			},
			artifacts: {
				type: "array",
				items: {
					type: "object",
					additionalProperties: false,
					required: ["path", "mediaType"],
					properties: {
						path: { type: "string" },
						mediaType: { type: "string" },
					},
				},
			},
		},
	},
	"role-result": {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		type: "object",
		additionalProperties: false,
		required: [
			"schemaVersion",
			"kind",
			"taskId",
			"role",
			"status",
			"headSha",
			"dirty",
			"changedPaths",
			"commands",
			"evidenceRefs",
			"artifactRefs",
			"blockers",
			"residualRisks",
		],
		properties: {
			schemaVersion: { const: 1 },
			kind: { const: "role-result" },
			taskId: { type: "string" },
			role: { type: "string" },
			status: { type: "string", enum: ["completed", "blocked", "failed", "unknown"] },
			headSha: { type: "string" },
			dirty: { type: "boolean" },
			changedPaths: { type: "array", items: { type: "string" } },
			commands: { type: "array" },
			evidenceRefs: { type: "array", items: { type: "string" } },
			artifactRefs: { type: "array", items: { type: "string" } },
			blockers: { type: "array", items: { type: "string" } },
			residualRisks: { type: "array", items: { type: "string" } },
			usage: {},
			redCause: { type: "object", additionalProperties: false },
		},
	},
	"approval-request": {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		type: "object",
		additionalProperties: false,
		required: [
			"schemaVersion",
			"kind",
			"requestId",
			"action",
			"risk",
			"scopedPaths",
			"candidateSha",
			"fingerprint",
			"requestedAt",
			"expiresAt",
		],
		properties: {
			schemaVersion: { const: 1 },
			kind: { const: "approval-request" },
			requestId: { type: "string" },
			action: { type: "string" },
			risk: { type: "string" },
			scopedPaths: { type: "array", items: { type: "string" } },
			candidateSha: { type: "string" },
			fingerprint: { type: "string" },
			requestedAt: { type: "string" },
			expiresAt: { type: "string" },
		},
	},
	"approval-decision": {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		type: "object",
		additionalProperties: false,
		required: [
			"schemaVersion",
			"kind",
			"requestId",
			"decision",
			"action",
			"risk",
			"scopedPaths",
			"candidateSha",
			"fingerprint",
			"decidedAt",
		],
		properties: {
			schemaVersion: { const: 1 },
			kind: { const: "approval-decision" },
			requestId: { type: "string" },
			decision: { type: "string", enum: ["approved", "rejected"] },
			action: { type: "string" },
			risk: { type: "string" },
			scopedPaths: { type: "array", items: { type: "string" } },
			candidateSha: { type: "string" },
			fingerprint: { type: "string" },
			decidedAt: { type: "string" },
			humanProvenance: { type: "object" },
		},
	},
	"validation-contract": {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		type: "object",
		additionalProperties: false,
		required: [
			"schemaVersion",
			"kind",
			"packageId",
			"focusedCommand",
			"expectedTestId",
			"matchMode",
			"coveringGreen",
			"forbiddenProductionPathsBeforeRed",
			"sensitivity",
		],
		properties: {
			schemaVersion: { const: 1 },
			kind: { const: "validation-contract" },
			packageId: { type: "string" },
			focusedCommand: { type: "string" },
			expectedTestId: { type: "string" },
			expectedFailureSignature: { type: "string" },
			matchMode: { type: "string", enum: ["identity", "signature"] },
			coveringGreen: { type: "object" },
			forbiddenProductionPathsBeforeRed: { type: "array", items: { type: "string" } },
			sensitivity: { type: "object" },
		},
	},
};
