Feature: Canonical Rulesync governance and root assurance
  The dotfiles repository needs one deterministic source for generated always-on rules
  and a real root assurance command before higher-risk workflow packages begin.

  Scenario: Missing canonical rule source is a causal red
    Given the GOV-01 contract test exists
    And production governance files do not exist
    When the focused GOV-01 test runs
    Then it fails at test_canonical_rules_contract_exists
    And the failure says rulesync.jsonc is missing
    And it does not fail because of import, setup, timeout, or command-not-found

  Scenario: Rulesync execution is pinned and local
    Given Rulesync 16.9.1 is declared exactly
    When a generate or drift-check wrapper runs
    Then it invokes node_modules/.bin/rulesync
    And a missing binary exits 127 without installing anything
    And a different version fails before generation

  Scenario: Generation is deterministic
    Given valid canonical input in a temporary repository
    When Rulesync generation runs twice
    Then the generated byte map is identical
    And AGENTS.md is the only generated target outside the canonical source tree

  Scenario: Direct generated-file edits are rejected
    Given AGENTS.md matches canonical input
    When AGENTS.md is changed directly
    Then Rulesync check exits non-zero
    And regenerating from canonical input restores the governed output

  Scenario: Root BDD command is executable and comprehensive
    Given root .pi/bdd.json exists
    When bdd-mode reads its unit command
    Then it runs scripts/test-root.sh
    And the script runs Python contracts, Pi tests, personal Pi library tests, and repository AI-resource validation
    And any child failure fails the root command

  Scenario: Rules and reusable resources keep separate owners
    Given Rulesync generates the root AGENTS.md
    Then the generated rule names rulesync.jsonc and .rulesync as always-on rule source
    And it names agents-shared/.agents as reusable resource source
    And GOV-01 does not generate vendor stow-package configuration
